name: CI/CD Workflow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: sebimih/tremend

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Git Repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta_python
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.IMAGE_NAME }}
        flavor: |
          latest=auto
          prefix=python-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./Task-2/python/
        file: ./Task-2/python/Dockerfile
        push: true
        tags: ${{ steps.meta_python.outputs.tags }}
        labels: ${{ steps.meta_python.outputs.labels }}

  java:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Git Repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta_java
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.IMAGE_NAME }}
        flavor: |
          latest=auto
          prefix=java-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./Task-2/java/
        file: ./Task-2/java/Dockerfile
        push: true
        tags: ${{ steps.meta_java.outputs.tags }}
        labels: ${{ steps.meta_java.outputs.labels }}